/** The archive's founding documents. Mixed RU/EN on purpose. */

export type SeedYap = {
  text: string;
  author: string;
  daysAgo: number;
  hour: number;
  minute: number;
  tags: string[];
  lore?: string;
  /** 0..1 — how hard the office reacted. Drives seeded reaction volume. */
  heat: number;
  evidence?: { kind: "chat" | "screen"; lines: string[]; caption: string };
  classification?: "ROUTINE" | "QUESTIONABLE" | "UNHINGED" | "CLASSIFIED";
  /** A formal dispute filed by the person the record is about. */
  dispute?: { statement?: string };
  /**
   * Pins corroboration for records the demo relies on. Without this a change
   * anywhere in the seed shifts the PRNG stream and the showcase records drift
   * into whatever state the lottery hands them.
   */
  testimony?: { witnesses: number; denials?: number };
};

/**
 * One of them is deliberately left without credentials: a person who is quoted
 * here but has never registered. That is the ordinary state of a real archive —
 * someone gets put on the record before they ever sign in — and it is what the
 * claim flow on /register exists for.
 */
export const UNCLAIMED_YAPPER = "Yulia";

export const YAPPERS = [
  { name: "Anna", handle: "anna", title: "professional yapper" },
  { name: "Misha", handle: "misha", title: "vibe-driven development" },
  { name: "Pasha", handle: "pasha", title: "works on my machine" },
  { name: "Dima", handle: "dima", title: "archivist" },
  { name: "Kate", handle: "kate", title: "let's circle back" },
  { name: "Sasha", handle: "sasha", title: "product, allegedly" },
  { name: "Lena", handle: "lena", title: "keeper of legacy" },
  { name: "Max", handle: "max", title: "not a designer, but" },
  { name: "Nikita", handle: "nikita", title: "two hours, tops" },
  { name: "Olya", handle: "olya", title: "five-minute standup" },
  { name: "Vlad", handle: "vlad", title: "it's documented" },
  { name: "Rita", handle: "rita", title: "database whisperer" },
  { name: "Timur", handle: "timur", title: "just one more if" },
  { name: "Yulia", handle: "yulia", title: "approved in my head" },
];

/** Reaction-only colleagues, so counts look like an actual office. */
export const AUDIENCE = [
  "Artem", "Полина", "Denis", "Marina", "Igor", "Света", "Roman", "Alina",
  "Serge", "Даша", "Egor", "Vera", "Boris", "Ксюша", "Ilya", "Natasha",
  "Fedor", "Женя", "Gleb", "Sonya", "Kirill", "Люба", "Andrei", "Masha",
  "Stepan", "Настя", "Oleg", "Julia", "Matvey", "Таня", "Grisha", "Nina",
  "Slava", "Алёна", "Zhenya", "Inna", "Valera", "Юра", "Kostya", "Dasha",
];


export const YAPS: SeedYap[] = [
  {
    text: "Плесень хайпует.",
    author: "Anna",
    // The founding incident sits a month back, not yesterday: it is the
    // archive's origin story, and leaving it on top made every default view
    // read as though this office only ever discussed mould.
    daysAgo: 28,
    hour: 14,
    minute: 37,
    tags: ["плесень", "хайп", "классика", "дизайн"],
    heat: 1,
    testimony: { witnesses: 4 },
    classification: "CLASSIFIED",
    lore: "Сказано во время обсуждения нового дизайна. Кто-то показал сырую версию макета, и на фотографии в хедере была плесень. Никто не стал её убирать. С этого момента «плесень» — отдельная сущность в нашей вселенной.",
    evidence: {
      kind: "chat",
      lines: ["Anna  14:37", "плесень хайпует", "Dima  14:37", "запиши это", "Anna  14:38", "зачем"],
      caption: "Рабочий чат, 24 сентября",
    },
  },
  {
    text: "Рот ставлю.",
    author: "Anna",
    daysAgo: 8,
    hour: 11,
    minute: 2,
    tags: ["легендарное", "рот", "база"],
    heat: 0.95,
    testimony: { witnesses: 2, denials: 2 },
    classification: "UNHINGED",
    lore: "Сказано в обсуждении, деплоить ли в пятницу.\n\nЗадеплоили.\n\nПрод лёг.",
  },
  {
    text: "Давай закроем это на вайбе.",
    author: "Misha",
    daysAgo: 14,
    hour: 16,
    minute: 21,
    tags: ["продакшн", "вайб", "риски"],
    heat: 0.88,
    testimony: { witnesses: 0 },
    lore: "Речь шла о миграции базы. Вайб не помог.",
  },
  {
    text: "Интернет вывезет.",
    author: "Misha",
    daysAgo: 23,
    hour: 12,
    minute: 9,
    tags: ["инфра", "надежда", "cdn"],
    heat: 0.85,
    lore: "Ответ на вопрос «мы точно не хотим CDN?». Интернет не вывез. Интернет отдал 12 мегабайт JPEG каждому посетителю лендинга.",
  },
  {
    text: "Это не баг, это фича.",
    author: "Pasha",
    daysAgo: 31,
    hour: 10,
    minute: 44,
    tags: ["классика", "баг", "фича"],
    heat: 0.8,
  },
  {
    text: "Мы просто на вайбе.",
    author: "Anna",
    daysAgo: 5,
    hour: 18,
    minute: 3,
    tags: ["вайб", "процессы"],
    heat: 0.78,
  },
  {
    text: "I'll just push it to prod, it's basically a typo fix.",
    author: "Dima",
    daysAgo: 12,
    hour: 19,
    minute: 48,
    tags: ["prod", "famous-last-words", "friday"],
    heat: 0.82,
    lore: "It was not, in any meaningful sense, a typo fix. It touched 41 files and one of them was the auth middleware.",
    evidence: {
      kind: "screen",
      lines: ["deploy #1184", "41 files changed", "status: FAILED", "rollback: manual"],
      caption: "Пайплайн, 19:51",
    },
  },
  {
    text: "Если не смотреть на метрики, то всё хорошо.",
    author: "Kate",
    daysAgo: 19,
    hour: 13,
    minute: 15,
    tags: ["метрики", "оптимизм"],
    heat: 0.74,
  },
  {
    text: "Работает у меня.",
    author: "Pasha",
    daysAgo: 27,
    hour: 9,
    minute: 58,
    tags: ["классика", "локально"],
    heat: 0.7,
  },
  {
    text: "Давайте просто перезапустим.",
    author: "Sasha",
    daysAgo: 4,
    hour: 15,
    minute: 32,
    tags: ["инфра", "решение"],
    heat: 0.55,
  },
  {
    text: "Это легаси, его нельзя трогать. Его написали в июне.",
    author: "Lena",
    daysAgo: 16,
    hour: 11,
    minute: 27,
    tags: ["легаси", "археология"],
    heat: 0.86,
    lore: "На момент фразы был сентябрь.",
  },
  {
    text: "Я не дизайнер, но кнопка должна быть больше.",
    author: "Max",
    daysAgo: 9,
    hour: 17,
    minute: 12,
    tags: ["дизайн", "кнопка"],
    heat: 0.68,
  },
  {
    text: "Let's circle back on this after the vibe check.",
    author: "Kate",
    daysAgo: 6,
    hour: 10,
    minute: 5,
    tags: ["meeting", "vibe", "corporate"],
    heat: 0.72,
  },
  {
    text: "У нас нет техдолга, у нас есть характер.",
    author: "Dima",
    daysAgo: 35,
    hour: 14,
    minute: 2,
    tags: ["техдолг", "характер"],
    heat: 0.9,
    classification: "UNHINGED",
  },
  {
    text: "Тесты? У нас есть пользователи.",
    author: "Misha",
    daysAgo: 41,
    hour: 16,
    minute: 40,
    tags: ["тесты", "qa", "классика"],
    heat: 0.84,
  },
  {
    text: "Слушай, ну это же очевидно.",
    author: "Pasha",
    dispute: {},
    daysAgo: 21,
    hour: 12,
    minute: 51,
    tags: ["онбординг", "очевидно"],
    heat: 0.6,
    lore: "Это не было очевидно. Это не было очевидно вообще никому, включая автора, что выяснилось через сорок минут.",
  },
  {
    text: "Я всё задокументировал.",
    author: "Vlad",
    dispute: {
      statement: "Документация существовала. Её удалили при переносе вики. Это другое.",
    },
    daysAgo: 48,
    hour: 18,
    minute: 22,
    tags: ["документация", "ложь"],
    heat: 0.76,
    lore: "Документация состояла из одного файла README.md, в котором было написано «TODO».",
  },
  {
    text: "Это займёт два часа.",
    author: "Nikita",
    dispute: { statement: "Я сказал «часа два», а не «два часа». Это принципиально разные вещи." },
    daysAgo: 55,
    hour: 11,
    minute: 8,
    tags: ["оценка", "сроки"],
    heat: 0.8,
    lore: "Заняло три недели. Из них две — на то, чтобы понять, почему первая неделя не сработала.",
  },
  {
    text: "Ship it, we'll fix it in the retro.",
    author: "Kate",
    daysAgo: 13,
    hour: 15,
    minute: 44,
    tags: ["agile", "retro", "ship"],
    heat: 0.71,
  },
  {
    text: "Мне кажется, база этого не переживёт.",
    author: "Rita",
    daysAgo: 7,
    hour: 13,
    minute: 36,
    tags: ["база", "предчувствие"],
    heat: 0.66,
    lore: "База не пережила. Рита теперь говорит «я же сказала» примерно раз в неделю, и это справедливо.",
  },
  {
    text: "Кто трогал прод? — Никто.",
    author: "Olya",
    daysAgo: 3,
    hour: 9,
    minute: 14,
    tags: ["прод", "расследование"],
    heat: 0.79,
  },
  {
    text: "Просто добавь ещё один if.",
    author: "Timur",
    daysAgo: 29,
    hour: 20,
    minute: 6,
    tags: ["архитектура", "if"],
    heat: 0.73,
  },
  {
    text: "Дизайн согласован. В голове.",
    author: "Yulia",
    daysAgo: 11,
    hour: 12,
    minute: 30,
    tags: ["дизайн", "согласование"],
    heat: 0.69,
  },
  {
    text: "It works, I don't know why, don't touch it.",
    author: "Dima",
    daysAgo: 38,
    hour: 22,
    minute: 17,
    tags: ["magic", "legacy", "prod"],
    heat: 0.87,
    classification: "CLASSIFIED",
  },
  {
    text: "Всё, я в потоке, не пишите.",
    author: "Anna",
    daysAgo: 1,
    hour: 10,
    minute: 55,
    tags: ["поток", "фокус"],
    heat: 0.5,
  },
  {
    text: "Мы это уже обсуждали на созвоне, которого не было.",
    author: "Misha",
    daysAgo: 18,
    hour: 14,
    minute: 24,
    tags: ["созвон", "память"],
    heat: 0.83,
  },
  {
    text: "Данные есть, но они в другом формате. В голове у Паши.",
    author: "Lena",
    daysAgo: 25,
    hour: 16,
    minute: 11,
    tags: ["данные", "паша"],
    heat: 0.75,
  },
  {
    text: "Синьор — это состояние души.",
    author: "Max",
    daysAgo: 44,
    hour: 19,
    minute: 2,
    tags: ["грейды", "философия"],
    heat: 0.67,
  },
  {
    text: "Давайте зафиксируем и никогда не вернёмся.",
    author: "Sasha",
    daysAgo: 10,
    hour: 11,
    minute: 49,
    tags: ["процессы", "решение"],
    heat: 0.64,
  },
  {
    text: "Я не спорю, я уточняю.",
    author: "Kate",
    daysAgo: 33,
    hour: 13,
    minute: 58,
    tags: ["дискуссия", "уточнение"],
    heat: 0.62,
  },
  {
    text: "Прод — это тоже стейдж, если не бояться.",
    author: "Pasha",
    daysAgo: 52,
    hour: 21,
    minute: 33,
    tags: ["прод", "философия", "страх"],
    heat: 0.89,
    classification: "UNHINGED",
    lore: "Сказано в 21:33 в пятницу. К 22:10 это перестало быть шуткой.",
  },
  {
    text: "Мы не переписываем, мы переосмысляем.",
    author: "Rita",
    daysAgo: 20,
    hour: 10,
    minute: 41,
    tags: ["рефакторинг", "переосмысление"],
    heat: 0.7,
  },
  {
    text: "Перфоманс нормальный, просто ноутбук старый.",
    author: "Timur",
    daysAgo: 15,
    hour: 15,
    minute: 19,
    tags: ["перфоманс", "ноутбук"],
    heat: 0.65,
  },
  {
    text: "Стендап на пять минут.",
    author: "Olya",
    daysAgo: 2,
    hour: 10,
    minute: 1,
    tags: ["стендап", "время"],
    heat: 0.77,
    lore: "46 минут.",
  },
  {
    text: "Я это в проде проверил, ничего не случилось.",
    author: "Nikita",
    daysAgo: 26,
    hour: 17,
    minute: 55,
    tags: ["прод", "проверка"],
    heat: 0.81,
    lore: "Случилось. Через сорок минут. У всех.",
  },
  {
    text: "Он не упал, он прилёг.",
    author: "Dima",
    daysAgo: 6,
    hour: 23,
    minute: 12,
    tags: ["сервер", "эвфемизм"],
    heat: 0.86,
  },
  {
    text: "Это не срочно, но нужно сегодня.",
    author: "Yulia",
    daysAgo: 17,
    hour: 9,
    minute: 37,
    tags: ["приоритеты", "срочно"],
    heat: 0.72,
  },
  {
    text: "У нас аджайл, поэтому дедлайн вчера.",
    author: "Vlad",
    daysAgo: 30,
    hour: 12,
    minute: 14,
    tags: ["agile", "дедлайн"],
    heat: 0.74,
  },
  {
    text: "Согласовано в переписке, которую удалили.",
    author: "Lena",
    daysAgo: 40,
    hour: 14,
    minute: 46,
    tags: ["согласование", "архив"],
    heat: 0.68,
  },
  {
    text: "Просто накатим хотфикс на хотфикс.",
    author: "Misha",
    daysAgo: 22,
    hour: 18,
    minute: 59,
    tags: ["хотфикс", "стратегия"],
    heat: 0.71,
  },
  {
    text: "Я оптимист, я не смотрю в логи.",
    author: "Anna",
    daysAgo: 36,
    hour: 11,
    minute: 23,
    tags: ["логи", "оптимизм"],
    heat: 0.84,
  },
  {
    text: "Честно, я думал, что это уже кто-то сделал.",
    author: "Max",
    daysAgo: 45,
    hour: 16,
    minute: 8,
    tags: ["ответственность", "надежда"],
    heat: 0.63,
  },
  {
    text: "Let's not over-engineer it.",
    author: "Kate",
    daysAgo: 50,
    hour: 13,
    minute: 27,
    tags: ["architecture", "irony"],
    heat: 0.78,
    lore: "Said while adding a fourth abstraction layer to a function that formats a date.",
  },
  {
    text: "Мы не теряем пользователей, мы их фильтруем.",
    author: "Sasha",
    daysAgo: 60,
    hour: 15,
    minute: 5,
    tags: ["метрики", "продукт", "фильтр"],
    heat: 0.88,
    classification: "CLASSIFIED",
    evidence: {
      kind: "screen",
      lines: ["DAU", "-34%", "retention d7", "-19%", "vibes", "стабильно"],
      caption: "Дашборд, который больше не открывают",
    },
  },
  {
    text: "Раньше мы такого не записывали.",
    author: "Dima",
    daysAgo: 365,
    hour: 12,
    minute: 15,
    tags: ["архив", "история", "раньше"],
    heat: 0.66,
    lore: "Сказано ровно за год до того, как архив всё-таки завели.",
  },
  {
    text: "Через год никто и не вспомнит.",
    author: "Kate",
    daysAgo: 365,
    hour: 17,
    minute: 48,
    tags: ["память", "прогноз", "классика"],
    heat: 0.81,
    testimony: { witnesses: 3 },
    lore: "Вспомнили. Ровно через год, на этой самой странице.",
  },
  {
    text: "Это временное решение.",
    author: "Pasha",
    daysAgo: 366,
    hour: 10,
    minute: 32,
    tags: ["временное", "прод", "легаси"],
    heat: 0.74,
    lore: "Решение проработало без изменений весь следующий год.",
  },
  {
    text: "Запиши это.",
    author: "Dima",
    daysAgo: 28,
    hour: 14,
    minute: 37,
    tags: ["плесень", "архив", "основание"],
    heat: 0.62,
    lore: "Момент, в который Yapped стал неизбежен.",
  },
  {
    text: "Зачем?",
    author: "Anna",
    daysAgo: 28,
    hour: 14,
    minute: 38,
    tags: ["плесень", "вопрос"],
    heat: 0.55,
  },
  {
    text: "Уберите плесень с макета.",
    author: "Yulia",
    daysAgo: 27,
    hour: 11,
    minute: 4,
    tags: ["плесень", "дизайн", "просьба"],
    heat: 0.58,
  },
  {
    text: "Плесень — это фича.",
    author: "Misha",
    daysAgo: 27,
    hour: 11,
    minute: 9,
    tags: ["плесень", "фича", "классика"],
    heat: 0.72,
    lore: "Плесень осталась на макете ещё на две недели.",
  },
  {
    text: "Ну мы же договорились.",
    author: "Olya",
    daysAgo: 43,
    hour: 10,
    minute: 18,
    tags: ["договорённости", "память"],
    heat: 0.58,
  },
  {
    text: "Почему в проде тестовые данные? — Для реализма.",
    author: "Timur",
    daysAgo: 58,
    hour: 19,
    minute: 41,
    tags: ["прод", "данные", "реализм"],
    heat: 0.85,
    lore: "В базе продакшена три недели жил пользователь «Тест Тестович Тестов» с балансом 999 999 ₽. Его нашли только потому, что он попал в топ лидерборда.",
  },
];
